import re

def convert_opcode_to_enum(opcode_str):
    match = re.match(r"#define\s+(\w+)\s+(\d+)", opcode_str)
    if match:
        return f"{match.group(1)} = {match.group(2)}"

def main():
    with open("opcode_ids.h", "r") as file:
        lines = file.readlines()

    print("// This file was generated by tools/bytecodeinst.py\n// DO NOT EDIT\n")
    print("pub const Inst = enum(u10) {")
    for line in lines:
        enum_entry = convert_opcode_to_enum(line)
        if enum_entry:
            print(f"    {enum_entry},")
    print("};")

if __name__ == "__main__":
    main()
