on:
  pull_request:
  push:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      
      - name: Setup Python3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/zig
            .zig-cache
          key: osmium-${{hashFiles('build.zig.zon')}}    

      - name: Build Osmium
        run: zig build

      - name: Run Behaviour Tests
        run: zig build test --summary all

      - name: Save Cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cache/zig
            .zig-cache
          key: osmium-${{hashFiles('build.zig.zon')}}         